@url = http://127.0.0.1

### Success Request ###
POST {{url}}:3005
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIiLCJzdWIiOiJtZSIsImV4cCI6MH0.41l_w0ADr1or25o-JvBMb4og4mF-nUolVtCTC7__7nI
X-REQUEST-TYPE: GraphQL

query {
    books {
        id
        desc {
            publisher {
                location {
                    flatAddress
                }
            }
        }
    }
}

### BAD Authorization ###
POST {{url}}:3004
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
    books {
        id
        desc {
            publisher {
                location {
                    flatAddress
                }
            }
        }
    }
}

### Depth Limit Error ###
POST {{url}}:3004
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIiLCJzdWIiOiJtZSIsImV4cCI6MH0.41l_w0ADr1or25o-JvBMb4og4mF-nUolVtCTC7__7nI
X-REQUEST-TYPE: GraphQL

query {
    books {
        id
        desc {
            publisher {
                location {
                    flatAddress
                    address {hello}
                }
            }
        }
    }
}


###
POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
    fullName: nameWithOwner
    description
    diskUsage
    forkCount
    stargazers(first: 5) {
        totalCount
        nodes {
            login
            name
        }
    }
    watchers {
        totalCount
    }
  }
}

{
    "name": "vscode-restclient",
    "owner": "Huachao"
}