apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-analysis
  template:
    metadata:
      labels:
        app: gql-analysis
    spec:
      containers:
        - name: router-main
          image: router-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
              hostPort: 3004
        - name: gql-analyzer-sidecar
          image: gql-analyzer:latest
          imagePullPolicy: IfNotPresent
