apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-analysis
  template:
    metadata:
      labels:
        app: gql-analysis
    spec:
      containers:
        - name: gql-analysis
          image: elcrazy/gql_analysis:latest
          ports:
            - containerPort: 8000
