apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-analysis
  template:
    metadata:
      labels:
        app: gql-analysis
    spec:
      containers:
        - name: gql-server-main
          image: gql-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              hostPort: 3000
        - name: gql-analysis-sidecar
          image: gql-analysis:latest
          imagePullPolicy: IfNotPresent
