apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-analysis
  template:
    metadata:
      labels:
        app: gql-analysis
    spec:
      containers:
        - name: GQL_ANALYSIS_SIDECAR
          image: elcrazy/gql-analysis:15.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              hostPort: 3000
