apiVersion: v1
kind: Pod
metadata:
  name: gql-service-pod
  labels:
    app: gql-service
spec:
  containers:
    - name: gql-service
      image: gql-service:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 27017
          hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: my-gql-service
spec:
  selector:
    app: gql-service
  ports:
  - port: 27017
    targetPort: 27017

